### PR TITLE
Reduce page size to 50

### PR DESCRIPTION
**Pull request by andylolz**
Duplicate of https://github.com/IATI/IATI-Dashboard/pull/578.

### CODE REVIEW

**Review by nosvalds — APPROVED** [review]
Tested and works as expected locally. Putting in place on Dev servers now.

**Comment by nosvalds** [comment]
Looks okay on Dev servers. Put fix in place on Live server, should update with the daily run in the early AM Friday.

**Comment by PetyaKangalova** [comment]
Thanks so much @nosvalds

**Comment by nosvalds** [comment]
image

**Comment by andylolz** [comment]
That screenshot is from the [dashboard](http://dashboard.iatistandard.org/), I think. I don’t think [publishing stats](http://publishingstats.iatistandard.org/) has regenerated yet:
Screenshot 2021-03-12 at 09 30 36

**Comment by stevieflow** [comment]
Huge thanks for this fix @nosvalds @PetyaKangalova @andylolz - you've made a member of the community very happy to see more IATI stats!

And yes - waiting for the publisher stats to regenerate - and hoping it is populated from date of publication..

**Comment by stevieflow** [comment]
hmm - the pub stats have now refresh, but I can't see CGIAR or Northern Ireland Cooperation Overseas Ltd (for example) listed: http://publishingstats.iatistandard.org/summary_stats.html ...

**Comment by stevieflow** [comment]
hmm - the pub stats have now refresh, but I can't see CGIAR or Northern Ireland Cooperation Overseas Ltd (for example) listed: http://publishingstats.iatistandard.org/summary_stats.html ...

**Comment by nosvalds** [comment]
I've put the fix in place on the publishingstats server as well. Expect it will be fixed with tomorrow mornings refresh.

**Comment by nosvalds** [comment]
The refresh was actually this afternoon UK time. CGIAR/Nothern Ireland Cooperation Overseas Ltd are showing now:
http://publishingstats.iatistandard.org/summary_stats.html

**Comment by stevieflow** [comment]
Amazing, thanks

**Comment by andylolz** [comment]
Brill – looks good!

**Pull request merged**
